services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    restart: unless-stopped

    environment:
      POSTGRES_DB: Devops_tools
      POSTGRES_USER: Devops
      POSTGRES_PASSWORD: Devops@113

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations:ro
      - ./database/seed:/docker-entrypoint-initdb.d/seed:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Devops -d Devops_tools"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

